### ISSUE TITLE
TypeError: 'iv' is an invalid keyword argument for this function

### ISSUE THREAD

**Issue by R0LA1mRifcF8yAkk** [cerber-os/wire-backup-parser#2]
Hi, I can't seem to decrypt my backup...

It looks like something's up with the type of cipher used.

```
$ python3 parser.py -f ~/Documents/wire_backups/Wire-Backup_2020-07-27.desktop_wbu -g 'Group name' -o ~/Documents/wire_backups/parsed

Loading backup...
Parsing backup...
Generating stats...
Downloading assets...
  0%|                                                                                             | 0/3 [00:00<?, ?it/s]
Wire credentials are required to continue
Email: my@email.address
Password:
  0%|                                                                                             | 0/3 [00:55<?, ?it/s]
Traceback (most recent call last):
  File "parser.py", line 53, in <module>
    events.downloadAllAssetsInGroup(group=groups.getGroupByName(args.group),
  File "/Users/username/projects/wire-backup-parser/wirebackupparser/events.py", line 178, in downloadAllAssetsInGroup
    asset = self.session.downloadAsset(event.asset_key, key, event.asset_token)
  File "/Users/username/projects/wire-backup-parser/wirebackupparser/wireAPI.py", line 72, in downloadAsset
    return self._decryptImage(resp.content, assetKey)
  File "/Users/username/projects/wire-backup-parser/wirebackupparser/wireAPI.py", line 51, in _decryptImage
    cipher = AES.new(key, AES.MODE_CBC, iv=iv)
  File "/usr/local/lib/python3.8/site-packages/Crypto/Cipher/AES.py", line 95, in new
    return AESCipher(key, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/Crypto/Cipher/AES.py", line 59, in __init__
    blockalgo.BlockAlgo.__init__(self, _AES, key, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/Crypto/Cipher/blockalgo.py", line 141, in __init__
    self._cipher = factory.new(key, *args, **kwargs)
TypeError: 'iv' is an invalid keyword argument for this function
```

**Comment by Lachcim** [comment]
This is likely related to the `pycrypto` dependency in requirements.txt which [has not been maintained since October 2013](https://pypi.org/project/pycrypto/#history). The `iv` attribute was introduced in [pycryptodome 3.4](https://pypi.org/project/pycryptodome/3.4/). The `pycrypto` requirement should therefore be replaced with `pycryptodome`.

Can you verify that this is indeed the case?

**Comment by Lachcim** [comment]
Upon closer inspection, I noticed I wasn't even able to perform a clean installation with the obsolete dependency in place. The `pycrypto` package appears to have compatibility issues with newer environments.

Thank you for bringing this to our attention.

**Comment by R0LA1mRifcF8yAkk** [comment]
No problem, so you'll investigate the problem and release a fix, hopefully soon?

**Comment by Lachcim** [comment]
Commit bb48cbb fixes the issue, pull the repository and run pip.

**Comment by R0LA1mRifcF8yAkk** [comment]
Wow, fast work, thanks! I can access a computer in a few hours, will let you know of the results.

**Comment by R0LA1mRifcF8yAkk** [comment]
Now everything runs smoothly, thank you for this wonderful tool! The backups are useless if I decide to delete my account but this parser changes that.

**Comment by R0LA1mRifcF8yAkk** [comment]
One more thing... How could I decrypt private conversations? At the moment it seems the script only accepts `-g` as an option.
